### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by howardroark2018** [justjavac/layoutit#3]
I was unable to translate the application to English (US), and failed to find a version in the English Language. Can somebody help me out with this? Is there an English Version that already exists? Pl help me with it.

Thanks a lot!

**Comment by justjavac** [comment]
http://layoutit.com/

**Comment by howardroark2018** [comment]
Sorry to not being clear at first. But, boss, actually, I wanted the source code in english. Could I get the source code to download?

**Comment by howardroark2018** [comment]
Hello, could anyone help me with the above problem? I really need this, and it would be a big help if, I can get it resolved. 

Please.

Thanks a lot, in advance.

**Comment by howardroark2018** [comment]
????????!!
